### PR TITLE
Markup in entity

### LINKED ISSUE #162: xml-conduit can't handle ENTITY declarations with markup inside
howto.xml (simplified from a real-world DocBook file):
```
<?xml version="1.0" encoding="utf-8"?>  <!-- -*- nxml -*- -->
<!DOCTYPE article [
<!ENTITY bareyes "✔">
<!ENTITY yes "<phrase role='unicode yes'>✔</phrase>">
<!ENTITY no "<phrase role='unicode no'>✘</phrase>">
]>
<article>
  &bareyes;
  &yes;
  &no;
</article>
```
ghci:
```
*Text.XML.Unresolved Text.XML Text.XML.Cursor Text.XML.Cursor.Generic Text.XML.Stream.Parse Text.XML.Stream.Render Text.XML.Stream.Token Text.XML.Unresolved> Data.ByteString.Lazy.readFile "howto.xml" >>= return . Text.XML.parseLBS def
Left (UnresolvedEntityException (fromList ["no","yes"]))
```
As you can see `&bareyes;` resolves fine, but `&no;` and `&yes;` do not; it's because of the XML tags in the entity definition.

### PR DESCRIPTION
**Pull request by jgm**
This PR was primarily motivated by the need to fix #162.  I've encountered real-world XML files that this library cannot handle because of this limitation (including some sample DocBook files).

In testing, I discovered a case where the parser did not return at all (instead going into an infinite loop).  This came from the last line of `parseEntities` (now renamed `parseDeclarations`):
``` hs
         (skipWhile (\t -> t /= ']' && t /= '<') >> parseEntities front)
```
which could succeed without consuming any input.  (This code has been there for a while and was untouched by my recent changes.)

To avoid this, in a subsequent commit I rewrite the token parsers a bit, to avoid cases where malformed XML could cause a loop.  I also added `<?>` combinators to make the error information a bit more informative.

### CODE REVIEW

File: xml-conduit/src/Text/XML/Stream/Parse.hs [hunk 1]
```diff
@@ -476,14 +478,21 @@ conduitToken :: MonadThrow m => ParseSettings -> ConduitT T.Text (PositionRange,
 conduitToken = conduitParser . parseToken
 
 parseToken :: ParseSettings -> Parser Token
-parseToken settings = (char '<' >> parseLt) <|> TokenContent <$> parseContent settings False False
```
Comment (k0ral) [inline xml-conduit/src/Text/XML/Stream/Parse.hs:461]: Do I understand correctly, that the aim of replacing `<|>` with `case` expressions, is to ensure `<?>` reports the correct information in case of failure ? Is this what you meant by `Parsers have been rewritten to ensure
that failures occur where they should` ?

File: xml-conduit/test/unit.hs [hunk 2]
```diff
@@ -49,6 +52,7 @@ main = hspec $ do
         it "displays comments" testRenderComments
         it "conduit parser" testConduitParser
         it "can omit the XML declaration" omitXMLDeclaration
+        it "can doesn't hang on malformed entity declarations" malformedEntityDeclaration
```
Comment (k0ral) [inline xml-conduit/test/unit.hs:55]: I assume you meant `it "doesn't ..."` rather than `it "can doesn't ..."`.

File: xml-conduit/test/unit.hs [hunk 3]
```diff
@@ -740,6 +741,14 @@ resolvedInline = do
     Res.Document _ root2 _ <- return $ Res.parseLBS_ Res.def "<!DOCTYPE foo [<!ENTITY bar \"baz\">]><foo bar='&bar;'/>"
     root2 @?= Res.Element "foo" (Map.singleton "bar" "baz") []
 
+resolvedInlineComplex :: Assertion
+resolvedInlineComplex = do
+    Res.Document _ root _ <- return $ Res.parseLBS_ Res.def "<!DOCTYPE foo [<!ENTITY bar \"<p>baz &bim;</p>\"><!ENTITY bim \"Hello\">]><foo>&bar;</foo>"
+    root @?= Res.Element "foo" Map.empty [Res.NodeElement (Res.Element "p" Map.empty [Res.NodeContent "baz Hello"])]
+    Res.Document _ root2 _ <- return $ Res.parseLBS_ Res.def "<!DOCTYPE foo [<!ENTITY bar \"<p>baz</p>\">]><foo class=\"&bar;\"/>"
```
Comment (k0ral) [inline xml-conduit/test/unit.hs:761]: Shouln't this expand to `<foo class="<p>baz</p>"/>`, and thus be invalid as [character `<` is forbidden in attribute value](https://www.w3.org/TR/REC-xml/#NT-AttValue) ?

File: xml-conduit/src/Text/XML/Stream/Parse.hs (hunk 1 above)
Comment (jgm) [reply xml-conduit/src/Text/XML/Stream/Parse.hs:461]: I suspect that the case in `parseLt` is also slightly more performant: instead of testing for `?`, then `!`, then `/`, and only then for a name, we can just go right away to the right branch.  But I haven't rigorously measured this, so maybe it's not.

File: xml-conduit/test/unit.hs (hunk 2 above)
Comment (jgm) [reply xml-conduit/test/unit.hs:55]: Yes, fixing.

File: xml-conduit/test/unit.hs (hunk 3 above)
Comment (jgm) [reply xml-conduit/test/unit.hs:761]: I wasn't sure how to handle this.  The current code simply ignores non-textual content when expanding entities inside attributes.  Attributes are `(TName, [Content])`, so there's no way to include non-textual content with the current types.

I'm also not really sure how XML wants you to handle this case.

Comment (jgm) [reply xml-conduit/test/unit.hs:761]: I think you're right that XML wants you to expand this into an invalid document.  But it would be hard to do that without bigger changes to the types and functions.  We can't even raise an exception in the function that handles this (`tokenToEvent`).  We could leave the ContentEntity as it is, which would trigger an unresolved entity exception later, but this would be a pretty puzzling error to get when the entity is defined. A longer-term solution would be to add a parameter to ContentEntity that allows us to track why the entity wasn't expanded. This would allow us to raise a more informative exception later.  Or the plumbing could be rearranged so that an exception could be raised from `tokenToEvent`.

**Comment by k0ral** [comment]
I believe this change makes the code more difficult to follow [at least to me], thus to review and maintain. However, the existing code was admittedly already difficult to follow: short variable names (`es`, `ps`, `xs`, ...), many nested `case` expressions, low-level `go`-style recursions rather than high-level recursion schemes, ... "Fixing" it would involve a significant rewrite, and I feel it's fair to consider it off the scope of this change.
Bottomline: I am merging this change, thank you !

**Comment by jgm** [comment]
Thanks for merging.  I completely agree that it's not so easy to follow.  I tried to make minimal changes to what was there, but if done from the ground up it could be done better.  (Also, if we didn't need to worry about a limit on entity expansion, the entity expansion code could be dramatically simplified.)

**Comment by jgm** [comment]
Actually this is one place where parsec's need for an explicit `try` is an advantage over attoparsec's implicit `try`.  In parsec, you can do `(char '[' >> a) <|> b)` and if there's a failure in `a`, you'll get an error indicating that. In attoparsec, if there's a failure in `a` it will try `b` and report the error in that context, which is very misleading.  The `peekChar` here was a way of working around that limitation.

**Comment by jgm** [comment]
Any chance of a new release with these fixes?

**Comment by k0ral** [comment]
Released as [1.9.1.1](https://hackage.haskell.org/package/xml-conduit-1.9.1.1) . Sorry for the delay.
